### ISSUE TITLE
چطوری بازی دانلود کنم

### ISSUE THREAD

**Issue by smkplus** [oldpersiangames/oldpersiangames.github.io#2]
سلام داداچ من چطوری بازی دانلود کنم
بازی قدیمی ندارم کسی هم نمیشناسم
یه جعبه سی دی داشتم که خیلی وقت پیش دادم نون خشکه

**Comment by alihardan** [comment]
سلام. تا اطلاع ثانوی دانلود کردن فقط برای مشارکت‌کنندگان امکانپذیر هست.

**Comment by alihardan** [comment]
خبر خوب: اکنون همگان می‌توانند دانلود کنند.
