### ISSUE TITLE
تفاوت نسخه ها

### ISSUE THREAD

**Issue by alirezasalehizadeh** [oldpersiangames/oldpersiangames.github.io#3]
،سلام

چرا تو بعضی از بازی ها، نسخه ای که برای عنوان انگلیسی اومده با نسخه عنوان فارسی متفاوته؟

برای مثال، تو بازی کانتر نوین پندار، عنوان انگلیسی کانتر ۱.۶ هست ولی عنوان فارسی ۱.۸ ؟

**Comment by alihardan** [comment]
سلام. شرکت ایرانی با عدد متفاوتی نسخه‌گذاری کرده و دلیلش رو باید از خودشون پرسید!
